//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonAn
    {
        public string TenMonAn { get; set; }
        public int IdMonAn { get; set; }
        public string MoTa { get; set; }
        public decimal GiaBan { get; set; }
        public string AnhMonAn { get; set; }
        public int IdLoaiMonAn { get; set; }
        public string SDTTaiKhoan { get; set; }
        public int TrangThai { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
